### ISSUE TITLE
Scribble.Win32.vcxproj cannot be built on its own

### ISSUE THREAD

**Issue by TheSevenPens** [TheSevenPens/WinPenKit#80]
Building the project directly fails to find the native header:

```
main.cpp(26,10): error C1083: Cannot open include file: 'pen_session.h': No such file or directory
```

It builds through `WinPenKitNative.sln`, which is how it is meant to be built, so this is a convenience fault rather than a broken sample. It is pre-existing and unrelated to any recent change — the same before and after #64.

## Why it is worth fixing

It costs a minute of confusion to anyone who reaches for the obvious command, and the error names a missing file rather than a missing include path, which points at the wrong thing.

## Likely fix

An `AdditionalIncludeDirectories` entry pointing at `..\WinPenKit.Native\include`, so the project carries its own include path rather than inheriting one from the solution.
